### ISSUE TITLE
Needs BlockKit update to support arm64

### ISSUE THREAD

**Issue by SPopenko** [humblehacker/AutoLayoutDSL#1]
https://github.com/pandamonia/BlocksKit/issues/178

Suggested fix: change pod dependence to 
pod 'BlocksKit', :git => 'https://github.com/pandamonia/BlocksKit.git', :branch => 'next'

**Comment by humblehacker** [comment]
Thanks for the heads-up.  In my quick check, there doesn't appear to be a way to point to a particular branch when specifying dependencies in a podspec file.  I tried variations on this, to no avail:

```
  s.dependency 'BlocksKit', { :git => 'https://github.com/pandamonia/BlocksKit.git', :branch => 'next' }
```

I will, however, update to BlocksKit 2.0 so this pod will be ready when [BlocksKit Issue 178](https://github.com/pandamonia/BlocksKit/issues/178) is closed.

**Comment by SPopenko** [comment]
Cool, thanks. 

As temporary solution it probably could be done like two step changes:
1) spec
s.dependency 'BlocksKitNext'

2) in pod file:
pod 'BlocksKitNext', :git => 'https://github.com/pandamonia/BlocksKit.git', :branch => 'next'
pod 'AutoLayoutDSL'

based on this pos: thttp://stackoverflow.com/questions/16905112/cocoapods-dependency-in-pod-spec-not-working

**Comment by humblehacker** [comment]
BlocksKit 2.2 has been released with the necessary fixes.
